import Editor from "./editor/Editor";
import AmbientLightNode from "./editor/nodes/AmbientLightNode";
import AudioNode from "./editor/nodes/AudioNode";
import BoxColliderNode from "./editor/nodes/BoxColliderNode";
import DirectionalLightNode from "./editor/nodes/DirectionalLightNode";
import FloorPlanNode from "./editor/nodes/FloorPlanNode";
import GroundPlaneNode from "./editor/nodes/GroundPlaneNode";
import GroupNode from "./editor/nodes/GroupNode";
import HemisphereLightNode from "./editor/nodes/HemisphereLightNode";
import ImageNode from "./editor/nodes/ImageNode";
import KitPieceNode from "./editor/nodes/KitPieceNode";
import LinkNode from "./editor/nodes/LinkNode";
import MediaFrameNode from "./editor/nodes/MediaFrameNode";
import ModelNode from "./editor/nodes/ModelNode";
import ParticleEmitterNode from "./editor/nodes/ParticleEmitterNode";
import PointLightNode from "./editor/nodes/PointLightNode";
import SceneNode from "./editor/nodes/SceneNode";
import ScenePreviewCameraNode from "./editor/nodes/ScenePreviewCameraNode";
import SimpleWaterNode from "./editor/nodes/SimpleWaterNode";
import SkyboxNode from "./editor/nodes/SkyboxNode";
import SpawnerNode from "./editor/nodes/SpawnerNode";
import SpawnPointNode from "./editor/nodes/SpawnPointNode";
import SpotLightNode from "./editor/nodes/SpotLightNode";
import TriggerVolumeNode from "./editor/nodes/TriggerVolumeNode";
import VideoNode from "./editor/nodes/VideoNode";
import WayPointNode from "./editor/nodes/WayPointNode";
import MyAssetsSource from "./ui/assets/sources/MyAssetsSource";
import SketchfabSource from "./ui/assets/sources/SketchfabSource";
import AmbientLightNodeEditor from "./ui/properties/AmbientLightNodeEditor";
import AudioNodeEditor from "./ui/properties/AudioNodeEditor";
import BoxColliderNodeEditor from "./ui/properties/BoxColliderNodeEditor";
import DirectionalLightNodeEditor from "./ui/properties/DirectionalLightNodeEditor";
import FloorPlanNodeEditor from "./ui/properties/FloorPlanNodeEditor";
import GroundPlaneNodeEditor from "./ui/properties/GroundPlaneNodeEditor";
import GroupNodeEditor from "./ui/properties/GroupNodeEditor";
import HemisphereLightNodeEditor from "./ui/properties/HemisphereLightNodeEditor";
import ImageNodeEditor from "./ui/properties/ImageNodeEditor";
import KitPieceNodeEditor from "./ui/properties/KitPieceNodeEditor";
import LinkNodeEditor from "./ui/properties/LinkNodeEditor";
import MediaFrameNodeEditor from "./ui/properties/MediaFrameNodeEditor";
import ModelNodeEditor from "./ui/properties/ModelNodeEditor";
import ParticleEmitterNodeEditor from "./ui/properties/ParticleEmitterNodeEditor";
import PointLightNodeEditor from "./ui/properties/PointLightNodeEditor";
import SceneNodeEditor from "./ui/properties/SceneNodeEditor";
import ScenePreviewCameraNodeEditor from "./ui/properties/ScenePreviewCameraNodeEditor";
import SimpleWaterNodeEditor from "./ui/properties/SimpleWaterNodeEditor";
import SkyboxNodeEditor from "./ui/properties/SkyboxNodeEditor";
import SpawnerNodeEditor from "./ui/properties/SpawnerNodeEditor";
import SpawnPointNodeEditor from "./ui/properties/SpawnPointNodeEditor";
import SpotLightNodeEditor from "./ui/properties/SpotLightNodeEditor";
import TriggerVolumeNodeEditor from "./ui/properties/TriggerVolumeNodeEditor";
import VideoNodeEditor from "./ui/properties/VideoNodeEditor";
import WayPointNodeEditor from "./ui/properties/WayPointNodeEditor";

export function createEditor(api, settings) {
  const editor = new Editor(api, settings);

  editor.registerNode(SceneNode, SceneNodeEditor);
  editor.registerNode(GroupNode, GroupNodeEditor);
  editor.registerNode(ModelNode, ModelNodeEditor);
  editor.registerNode(GroundPlaneNode, GroundPlaneNodeEditor);
  editor.registerNode(BoxColliderNode, BoxColliderNodeEditor);
  editor.registerNode(AmbientLightNode, AmbientLightNodeEditor);
  editor.registerNode(DirectionalLightNode, DirectionalLightNodeEditor);
  editor.registerNode(HemisphereLightNode, HemisphereLightNodeEditor);
  editor.registerNode(SpotLightNode, SpotLightNodeEditor);
  editor.registerNode(PointLightNode, PointLightNodeEditor);
  editor.registerNode(SpawnPointNode, SpawnPointNodeEditor);
  editor.registerNode(WayPointNode, WayPointNodeEditor);
  editor.registerNode(SkyboxNode, SkyboxNodeEditor);
  editor.registerNode(FloorPlanNode, FloorPlanNodeEditor);
  editor.registerNode(ImageNode, ImageNodeEditor);
  editor.registerNode(VideoNode, VideoNodeEditor);
  editor.registerNode(AudioNode, AudioNodeEditor);
  editor.registerNode(SpawnerNode, SpawnerNodeEditor);
  editor.registerNode(TriggerVolumeNode, TriggerVolumeNodeEditor);
  editor.registerNode(LinkNode, LinkNodeEditor);
  editor.registerNode(ParticleEmitterNode, ParticleEmitterNodeEditor);
  editor.registerNode(KitPieceNode, KitPieceNodeEditor);
  editor.registerNode(SimpleWaterNode, SimpleWaterNodeEditor);
  editor.registerNode(ScenePreviewCameraNode, ScenePreviewCameraNodeEditor);
  editor.registerNode(MediaFrameNode, MediaFrameNodeEditor);
  editor.registerSource(new MyAssetsSource(editor));
  editor.registerSource(new SketchfabSource(api));

  return editor;
}
